# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-go-quark
  description: Buildkite Pipeline for go-quark
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/go-quark

spec:
  type: buildkite-pipeline
  owner: group:sec-linux-platform
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: go-quark
      description: 
    spec:
      repository: elastic/go-quark
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        sec-linux-platform:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
