---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "Triggering pipelines"
    plugins:
      monorepo-diff#v1.2.0:
        diff: ".buildkite/diff ${BUILDKITE_COMMIT}"
        wait: true
        watch:
          # if our Renovate configuration is amended, then make sure we have well-formed config
          # for more info, see https://docs.elastic.dev/plat-prod-team/service-catalogue/renovate/testing-renovate-changes
          - path: "renovate.json"
            config:
              label: "Verify Renovate configuration"
              command: "renovate-config-validator"
              agents:
                image: "docker.elastic.co/ci-agent-images/pipelib:0.10.0@sha256:83ddb7512b8950ead9f6c5a26335249a2b796e1fe534e248658c79874ad96067"
          # ... otherwise, fall back to the default pipeline
          - path: "**/*"
            config:
              label: ":pipeline: Upload default Pipeline"
              command: |
                if test "$(git log -1 --pretty=format:'%ae')" = "150874479+elastic-vault-github-plugin-prod[bot]@users.noreply.github.com"; then
                  echo "Last commit from bot; skipping pipeline"
                  exit 0
                fi
                buildkite-agent pipeline upload .buildkite/default-pipeline.yml
